version: '3.6'

services:
  app:
    build: .
    image: pivorak-multistage
    depends_on:
      - db
    env_file:
      - environment.docker
  db:
    image: postgres:9-alpine
    env_file:
      - environment.docker
